package top.laoxin.modmanager.constant

object UserPreferencesKeys {
    const val SELECTED_GAME = "SELECTED_GAME"
    const val SCAN_QQ_DIRECTORY = "SCAN_QQ_DIRECTORY"
    const val SELECTED_DIRECTORY = "SELECTED_DIRECTORY"
    const val SCAN_DOWNLOAD = "SCAN_DOWNLOAD"
    const val OPEN_PERMISSION_REQUEST_DIALOG = "OPEN_PERMISSION_REQUEST_DIALOG"
    const val SCAN_DIRECTORY_MODS = "SCAN_DIRECTORY_MODS"
    const val DELETE_UNZIP_DIRECTORY = "DELETE_UNZIP_DIRECTORY"
    const val SHOW_CATEGORY_VIEW = "SHOW_CATEGORY_VIEW"
    const val USER_TIPS = "USER_TIPS"
}